// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2hs3q6W18baQ8iYRpxeLN1lWcxjPb574',
    appId: '1:919111653522:web:6c9ea4ae51a65eed1f6e4b',
    messagingSenderId: '919111653522',
    projectId: 'pos-system-ff2e0',
    authDomain: 'pos-system-ff2e0.firebaseapp.com',
    storageBucket: 'pos-system-ff2e0.appspot.com',
    measurementId: 'G-DWNQ9SKMEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzSEMOcaQPmVhfa4vQgy0ZQ_ASqAYqKPY',
    appId: '1:919111653522:android:d93497197541cd2e1f6e4b',
    messagingSenderId: '919111653522',
    projectId: 'pos-system-ff2e0',
    storageBucket: 'pos-system-ff2e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2YEtEQDRhE5x_KIa_mrzsgs56GrozeEs',
    appId: '1:919111653522:ios:6d6e17d0818585c71f6e4b',
    messagingSenderId: '919111653522',
    projectId: 'pos-system-ff2e0',
    storageBucket: 'pos-system-ff2e0.appspot.com',
    iosBundleId: 'com.technogenis.posSystem',
  );
}
